// Package groundtruth checks the catalog against facts read from the Kubernetes source rather
// than from release notes.
//
// This is the test that makes the catalog trustworthy. Every other test proves the code does
// what the catalog says; this one proves the catalog says what Kubernetes does. The fixtures are
// generated by scripts/gen-k8s-groundtruth.py from two machine-readable places in the upstream
// repository: the generated lifecycle functions that decide when the API server stops serving a
// kind, and the feature-gate registry, diffed across release tags.
//
// Release notes were the original source and were wrong often enough to matter. A gate under-
// reported in a changelog becomes a rule that never fires; a removal listed at the wrong minor
// becomes a critical finding against an API that still works.
package groundtruth

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"

	"github.com/runtimez-com/kube-upgrade-check/internal/catalog"
)

// gateFloor is where feature-gate reconciliation is complete and asserted exactly.
//
// Earlier releases still carry gaps inherited from the era when rules were transcribed from
// changelogs. Those are held under a ratchet rather than an allow-list, so the number can only
// fall.
const gateFloor = 1032

// knownPreFloorGateGaps is the current backlog below the floor. Closing any of these means
// lowering this number in the same commit.
const knownPreFloorGateGaps = 70

// lockedNotRemoved names gates upstream still registers but locks to their default. A locked
// gate catalogued as removed is a false critical claiming a component will not start, so moving
// one out of this set without re-banding its rule is meant to turn this test red.
var lockedNotRemoved = map[string]bool{"DeclarativeValidationTakeover": true}

func load(t *testing.T) *catalog.Catalog {
	t.Helper()
	cat, err := catalog.Load()
	if err != nil {
		t.Fatal(err)
	}
	return cat
}

// apiRemovals is every group-version-kind upstream stops serving, and when.
func apiRemovals(t *testing.T) []struct {
	APIVersion   string `json:"apiVersion"`
	Kind         string `json:"kind"`
	DeprecatedIn string `json:"deprecatedIn"`
	RemovedIn    string `json:"removedIn"`
} {
	t.Helper()
	var file struct {
		Data []struct {
			APIVersion   string `json:"apiVersion"`
			Kind         string `json:"kind"`
			DeprecatedIn string `json:"deprecatedIn"`
			RemovedIn    string `json:"removedIn"`
		} `json:"data"`
	}
	readFixture(t, "api-removals.json", &file)
	return file.Data
}

// gateRemovals maps a version to the feature gates that disappeared in it.
func gateRemovals(t *testing.T) map[string][]string {
	t.Helper()
	var file struct {
		Data map[string][]string `json:"data"`
	}
	readFixture(t, "gate-removals.json", &file)
	return file.Data
}

func readFixture(t *testing.T, name string, out any) {
	t.Helper()
	path := filepath.Join("..", "..", "..", "testdata", "groundtruth", name)
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	if err := json.Unmarshal(raw, out); err != nil {
		t.Fatalf("parse %s: %v", path, err)
	}
}

// cataloguedGateVersions maps each gate a rule names to the versions those rules claim.
func cataloguedGateVersions(cat *catalog.Catalog) map[string]map[string]bool {
	out := map[string]map[string]bool{}
	for _, rule := range cat.ConfigBreakers {
		if rule.Value == "" || !strings.HasPrefix(rule.Condition, "featureGate") {
			continue
		}
		gate := gateNameOf(rule.Value)
		if out[gate] == nil {
			out[gate] = map[string]bool{}
		}
		out[gate][rule.AppliesFromVersion] = true
	}
	return out
}

// gateNameOf strips the "=value" half of a locked-gate rule's value.
func gateNameOf(value string) string {
	name, _, _ := strings.Cut(value, "=")
	return name
}

func TestEveryRemovedGateAboveTheFloorIsCatalogued(t *testing.T) {
	cat := load(t)
	catalogued := cataloguedGateVersions(cat)
	ceiling := catalog.MinorKey(catalog.LatestKnownMinor)

	var gaps []string
	for version, gates := range gateRemovals(t) {
		key := catalog.MinorKey(version)
		if key < gateFloor || key > ceiling {
			continue
		}
		for _, gate := range gates {
			if versions := catalogued[gate]; !versions[version] {
				if len(versions) == 0 {
					gaps = append(gaps, fmt.Sprintf("%s %s (no rule at all)", version, gate))
				} else {
					gaps = append(gaps, fmt.Sprintf("%s %s (rules say %v)", version, gate, sortedKeys(versions)))
				}
			}
		}
	}
	sort.Strings(gaps)

	if len(gaps) > 0 {
		t.Errorf("Feature gates removed upstream with no matching rule. A component still passing one "+
			"of these in --feature-gates exits at startup, and without a rule the report shows it as "+
			"clean. Regenerate with scripts/gen-k8s-groundtruth.py, then add a rule per gate to "+
			"catalog/k8s-config-breakers/config-breakers.json:\n  %s", strings.Join(gaps, "\n  "))
	}
}

// The inverse direction, and the more dangerous one: a rule that claims a removal upstream does
// not support tells an operator their cluster will not start when it will.
func TestNoGateRuleContradictsGroundTruth(t *testing.T) {
	cat := load(t)
	removedAt := map[string]string{}
	for version, gates := range gateRemovals(t) {
		for _, gate := range gates {
			removedAt[gate] = version
		}
	}

	var wrong []string
	for _, rule := range cat.ConfigBreakers {
		if rule.Value == "" || !strings.HasPrefix(rule.Condition, "featureGate") {
			continue
		}
		gate := gateNameOf(rule.Value)
		if lockedNotRemoved[gate] {
			continue
		}
		// A locked-gate rule names a value, not a removal, so it is not making a removal claim.
		if strings.Contains(rule.Value, "=") {
			continue
		}
		truth, ok := removedAt[gate]
		switch {
		case !ok:
			wrong = append(wrong, fmt.Sprintf("%s: gate %q is still registered upstream, so it was never removed",
				rule.RuleID, gate))
		case truth != rule.AppliesFromVersion:
			wrong = append(wrong, fmt.Sprintf("%s: says %s, upstream removed it in %s",
				rule.RuleID, rule.AppliesFromVersion, truth))
		}
	}
	sort.Strings(wrong)

	if len(wrong) > 0 {
		t.Errorf("Rules whose removal claim upstream contradicts. Each is a false critical telling an "+
			"operator a component will not boot. A gate that is locked rather than removed belongs in "+
			"lockedNotRemoved with its rule re-banded:\n  %s", strings.Join(wrong, "\n  "))
	}
}

func TestPreFloorGateBacklogOnlyShrinks(t *testing.T) {
	cat := load(t)
	catalogued := cataloguedGateVersions(cat)

	var gaps []string
	for version, gates := range gateRemovals(t) {
		if catalog.MinorKey(version) >= gateFloor {
			continue
		}
		for _, gate := range gates {
			if !catalogued[gate][version] {
				gaps = append(gaps, version+" "+gate)
			}
		}
	}
	sort.Strings(gaps)

	if len(gaps) > knownPreFloorGateGaps {
		t.Errorf("The pre-1.32 gate backlog grew from %d to %d. Backfilling is welcome, and means "+
			"lowering knownPreFloorGateGaps in the same commit; adding new gaps is not:\n  %s",
			knownPreFloorGateGaps, len(gaps), strings.Join(gaps, "\n  "))
	}
	t.Logf("pre-1.32 gate backlog: %d of a permitted %d", len(gaps), knownPreFloorGateGaps)
}

func TestEveryRemovedApiIsCatalogued(t *testing.T) {
	cat := load(t)
	ceiling := catalog.MinorKey(catalog.LatestKnownMinor)

	var problems []string
	for _, row := range apiRemovals(t) {
		rule, hasRule := cat.DeprecationFor(row.APIVersion, row.Kind)
		life, hasLifecycle := cat.LifecycleFor(row.APIVersion, row.Kind)

		if !hasRule && !hasLifecycle {
			// The ceiling bounds missing rows only. A removal scheduled past the newest target
			// anyone can select cannot be acted on, so no row is owed yet.
			if catalog.MinorKey(row.RemovedIn) <= ceiling {
				problems = append(problems, fmt.Sprintf("%s %s %s — absent from both arrays",
					row.RemovedIn, row.APIVersion, row.Kind))
			}
			continue
		}

		// A row that EXISTS is checked at every version, ceiling or not. Bounding this by the
		// ceiling as well would blind the test to the case that motivates it: a removal scheduled
		// above the ceiling but catalogued below it fires a critical finding against an API that
		// is still served. The resolved value is what gets compared, so a kind inheriting a
		// wildcard row written for its siblings is caught too.
		if hasRule && rule.RemovedIn != row.RemovedIn {
			problems = append(problems, fmt.Sprintf("%s %s %s — the rule says %s",
				row.RemovedIn, row.APIVersion, row.Kind, rule.RemovedIn))
		}
		if hasLifecycle && life.RemovedIn != row.RemovedIn {
			problems = append(problems, fmt.Sprintf("%s %s %s — the detector table resolves to %s",
				row.RemovedIn, row.APIVersion, row.Kind, life.RemovedIn))
		}
	}
	sort.Strings(problems)

	if len(problems) > 0 {
		t.Errorf("Removed-API rows that disagree with upstream. Too early fires a critical against an "+
			"API that still works; too late clears an object that is already gone. Regenerate with "+
			"scripts/gen-k8s-groundtruth.py and reconcile catalog/k8s-deprecations/removed-apis.json:\n  %s",
			strings.Join(problems, "\n  "))
	}
}

// A fixture that silently emptied would make every test above pass for the wrong reason.
func TestFixturesAreLoadableAndSubstantial(t *testing.T) {
	if got := len(apiRemovals(t)); got < 50 {
		t.Errorf("api-removals.json has %d rows, expected well over 50", got)
	}
	if got := len(gateRemovals(t)); got < 10 {
		t.Errorf("gate-removals.json covers %d versions, expected more than 10", got)
	}
}

func sortedKeys(set map[string]bool) []string {
	out := make([]string, 0, len(set))
	for k := range set {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}
